### ISSUE TITLE
Sidebar layout

### ISSUE THREAD

**Issue by ghost** [Ryank2004/the-client-website#13]
De nav/sidebar snijdt af op bepaalde pagina's. Kijk ook nog even goed naar de layout en spacing van de icons/items in de sitebar. Deze zijn nu namelijk niet gecentreerd wanneer die is ingeklapt. 

![image](https://github.com/Ryank2004/the-client-website/assets/112856287/be6849cc-0621-4d9e-b7eb-333a40a1d096)
![image](https://github.com/Ryank2004/the-client-website/assets/112856287/4ab27967-c7a7-48f6-9f8e-1e3f50b42e91)

**Comment by koeenm** [comment]
we hebben de sidebar nu tot aan de footer laten lopen en de icons staan nu in het midden van de bar
